# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x06llm.v1\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xbf\x01\n\x0cStartRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\ndeployment\x18\x03 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x04 \x01(\t\x12%\n\x08messages\x18\x05 \x03(\x0b\x32\x13.llm.v1.ChatMessage\x12\x0e\n\x06stream\x18\x06 \x01(\x08\x12\x12\n\nmax_tokens\x18\x07 \x01(\r\x12\x13\n\x0btemperature\x18\x08 \x01(\x01\"\x1c\n\x06\x43\x61ncel\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"_\n\rClientMessage\x12%\n\x05start\x18\x01 \x01(\x0b\x32\x14.llm.v1.StartRequestH\x00\x12 \n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x0e.llm.v1.CancelH\x00\x42\x05\n\x03msg\"\x1f\n\tConnected\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x15\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x08Sentence\x12\x0c\n\x04text\x18\x01 \x01(\t\"O\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\r\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\r\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\r\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc4\x01\n\rServerMessage\x12&\n\tconnected\x18\x01 \x01(\x0b\x32\x11.llm.v1.ConnectedH\x00\x12\x1e\n\x05token\x18\x02 \x01(\x0b\x32\r.llm.v1.TokenH\x00\x12$\n\x08sentence\x18\x03 \x01(\x0b\x32\x10.llm.v1.SentenceH\x00\x12\x1e\n\x05usage\x18\x04 \x01(\x0b\x32\r.llm.v1.UsageH\x00\x12\x1e\n\x05\x65rror\x18\x05 \x01(\x0b\x32\r.llm.v1.ErrorH\x00\x42\x05\n\x03msg2B\n\x03LLM\x12;\n\x07Session\x12\x15.llm.v1.ClientMessage\x1a\x15.llm.v1.ServerMessage(\x01\x30\x01\x42\"Z yuzu/agent/internal/llm/pb;llmpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z yuzu/agent/internal/llm/pb;llmpb'
  _globals['_CHATMESSAGE']._serialized_start=21
  _globals['_CHATMESSAGE']._serialized_end=65
  _globals['_STARTREQUEST']._serialized_start=68
  _globals['_STARTREQUEST']._serialized_end=259
  _globals['_CANCEL']._serialized_start=261
  _globals['_CANCEL']._serialized_end=289
  _globals['_CLIENTMESSAGE']._serialized_start=291
  _globals['_CLIENTMESSAGE']._serialized_end=386
  _globals['_CONNECTED']._serialized_start=388
  _globals['_CONNECTED']._serialized_end=419
  _globals['_TOKEN']._serialized_start=421
  _globals['_TOKEN']._serialized_end=442
  _globals['_SENTENCE']._serialized_start=444
  _globals['_SENTENCE']._serialized_end=468
  _globals['_USAGE']._serialized_start=470
  _globals['_USAGE']._serialized_end=549
  _globals['_ERROR']._serialized_start=551
  _globals['_ERROR']._serialized_end=589
  _globals['_SERVERMESSAGE']._serialized_start=592
  _globals['_SERVERMESSAGE']._serialized_end=788
  _globals['_LLM']._serialized_start=790
  _globals['_LLM']._serialized_end=856
# @@protoc_insertion_point(module_scope)
