# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x06tts.v1\"V\n\x0cStartRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x10\n\x08voice_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\"\x1c\n\x06\x43\x61ncel\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"_\n\rClientMessage\x12%\n\x05start\x18\x01 \x01(\x0b\x32\x14.tts.v1.StartRequestH\x00\x12 \n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x0e.tts.v1.CancelH\x00\x42\x05\n\x03msg\"\x1f\n\tConnected\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x1c\n\nAudioChunk\x12\x0e\n\x06pcm48k\x18\x01 \x01(\x0c\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x83\x01\n\rServerMessage\x12&\n\tconnected\x18\x01 \x01(\x0b\x32\x11.tts.v1.ConnectedH\x00\x12#\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.tts.v1.AudioChunkH\x00\x12\x1e\n\x05\x65rror\x18\x03 \x01(\x0b\x32\r.tts.v1.ErrorH\x00\x42\x05\n\x03msg2B\n\x03TTS\x12;\n\x07Session\x12\x15.tts.v1.ClientMessage\x1a\x15.tts.v1.ServerMessage(\x01\x30\x01\x42\"Z yuzu/agent/internal/tts/pb;ttspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z yuzu/agent/internal/tts/pb;ttspb'
  _globals['_STARTREQUEST']._serialized_start=21
  _globals['_STARTREQUEST']._serialized_end=107
  _globals['_CANCEL']._serialized_start=109
  _globals['_CANCEL']._serialized_end=137
  _globals['_CLIENTMESSAGE']._serialized_start=139
  _globals['_CLIENTMESSAGE']._serialized_end=234
  _globals['_CONNECTED']._serialized_start=236
  _globals['_CONNECTED']._serialized_end=267
  _globals['_AUDIOCHUNK']._serialized_start=269
  _globals['_AUDIOCHUNK']._serialized_end=297
  _globals['_ERROR']._serialized_start=299
  _globals['_ERROR']._serialized_end=337
  _globals['_SERVERMESSAGE']._serialized_start=340
  _globals['_SERVERMESSAGE']._serialized_end=471
  _globals['_TTS']._serialized_start=473
  _globals['_TTS']._serialized_end=539
# @@protoc_insertion_point(module_scope)
