// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: gateway_control.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayControl_Session_FullMethodName = "/gateway.v1.GatewayControl/Session"
)

// GatewayControlClient is the client API for GatewayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayControlClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayEvent, OrchestratorCommand], error)
}

type gatewayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlClient(cc grpc.ClientConnInterface) GatewayControlClient {
	return &gatewayControlClient{cc}
}

func (c *gatewayControlClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayEvent, OrchestratorCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayControl_ServiceDesc.Streams[0], GatewayControl_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewayEvent, OrchestratorCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControl_SessionClient = grpc.BidiStreamingClient[GatewayEvent, OrchestratorCommand]

// GatewayControlServer is the server API for GatewayControl service.
// All implementations must embed UnimplementedGatewayControlServer
// for forward compatibility.
type GatewayControlServer interface {
	Session(grpc.BidiStreamingServer[GatewayEvent, OrchestratorCommand]) error
	mustEmbedUnimplementedGatewayControlServer()
}

// UnimplementedGatewayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServer struct{}

func (UnimplementedGatewayControlServer) Session(grpc.BidiStreamingServer[GatewayEvent, OrchestratorCommand]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedGatewayControlServer) mustEmbedUnimplementedGatewayControlServer() {}
func (UnimplementedGatewayControlServer) testEmbeddedByValue()                        {}

// UnsafeGatewayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServer will
// result in compilation errors.
type UnsafeGatewayControlServer interface {
	mustEmbedUnimplementedGatewayControlServer()
}

func RegisterGatewayControlServer(s grpc.ServiceRegistrar, srv GatewayControlServer) {
	// If the following call panics, it indicates UnimplementedGatewayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControl_ServiceDesc, srv)
}

func _GatewayControl_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayControlServer).Session(&grpc.GenericServerStream[GatewayEvent, OrchestratorCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControl_SessionServer = grpc.BidiStreamingServer[GatewayEvent, OrchestratorCommand]

// GatewayControl_ServiceDesc is the grpc.ServiceDesc for GatewayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayControl",
	HandlerType: (*GatewayControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _GatewayControl_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway_control.proto",
}
