// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gateway_control.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomUrl       string                 `protobuf:"bytes,2,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpen) Reset() {
	*x = SessionOpen{}
	mi := &file_gateway_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpen) ProtoMessage() {}

func (x *SessionOpen) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpen.ProtoReflect.Descriptor instead.
func (*SessionOpen) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{0}
}

func (x *SessionOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOpen) GetRoomUrl() string {
	if x != nil {
		return x.RoomUrl
	}
	return ""
}

type VADStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          uint64                 `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VADStart) Reset() {
	*x = VADStart{}
	mi := &file_gateway_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADStart) ProtoMessage() {}

func (x *VADStart) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADStart.ProtoReflect.Descriptor instead.
func (*VADStart) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{1}
}

func (x *VADStart) GetTsMs() uint64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type VADEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          uint64                 `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VADEnd) Reset() {
	*x = VADEnd{}
	mi := &file_gateway_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADEnd) ProtoMessage() {}

func (x *VADEnd) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADEnd.ProtoReflect.Descriptor instead.
func (*VADEnd) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{2}
}

func (x *VADEnd) GetTsMs() uint64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type TranscriptInterim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   string                 `protobuf:"bytes,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptInterim) Reset() {
	*x = TranscriptInterim{}
	mi := &file_gateway_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptInterim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptInterim) ProtoMessage() {}

func (x *TranscriptInterim) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptInterim.ProtoReflect.Descriptor instead.
func (*TranscriptInterim) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{3}
}

func (x *TranscriptInterim) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *TranscriptInterim) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscriptFinal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   string                 `protobuf:"bytes,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptFinal) Reset() {
	*x = TranscriptFinal{}
	mi := &file_gateway_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptFinal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptFinal) ProtoMessage() {}

func (x *TranscriptFinal) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptFinal.ProtoReflect.Descriptor instead.
func (*TranscriptFinal) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{4}
}

func (x *TranscriptFinal) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *TranscriptFinal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TTSEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                        // started | first_audio | stopped
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                    // if stopped
	FirstAudioMs  uint32                 `protobuf:"varint,3,opt,name=first_audio_ms,json=firstAudioMs,proto3" json:"first_audio_ms,omitempty"` // optional, only for first_audio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSEvent) Reset() {
	*x = TTSEvent{}
	mi := &file_gateway_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSEvent) ProtoMessage() {}

func (x *TTSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSEvent.ProtoReflect.Descriptor instead.
func (*TTSEvent) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{5}
}

func (x *TTSEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TTSEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TTSEvent) GetFirstAudioMs() uint32 {
	if x != nil {
		return x.FirstAudioMs
	}
	return 0
}

type GatewayError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayError) Reset() {
	*x = GatewayError{}
	mi := &file_gateway_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayError) ProtoMessage() {}

func (x *GatewayError) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayError.ProtoReflect.Descriptor instead.
func (*GatewayError) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GatewayError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FrameTap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm48K        []byte                 `protobuf:"bytes,1,opt,name=pcm48k,proto3" json:"pcm48k,omitempty"` // 20ms PCM16 mono at 48kHz
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameTap) Reset() {
	*x = FrameTap{}
	mi := &file_gateway_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameTap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameTap) ProtoMessage() {}

func (x *FrameTap) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameTap.ProtoReflect.Descriptor instead.
func (*FrameTap) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{7}
}

func (x *FrameTap) GetPcm48K() []byte {
	if x != nil {
		return x.Pcm48K
	}
	return nil
}

type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rms           float32                `protobuf:"fixed32,1,opt,name=rms,proto3" json:"rms,omitempty"` // root-mean-square energy for the 20ms frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_gateway_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{8}
}

func (x *Feature) GetRms() float32 {
	if x != nil {
		return x.Rms
	}
	return 0
}

type GatewayEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Evt:
	//
	//	*GatewayEvent_SessionOpen
	//	*GatewayEvent_VadStart
	//	*GatewayEvent_VadEnd
	//	*GatewayEvent_TranscriptInterim
	//	*GatewayEvent_TranscriptFinal
	//	*GatewayEvent_Tts
	//	*GatewayEvent_Error
	//	*GatewayEvent_FrameTap
	//	*GatewayEvent_Feature
	Evt           isGatewayEvent_Evt `protobuf_oneof:"evt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEvent) Reset() {
	*x = GatewayEvent{}
	mi := &file_gateway_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEvent) ProtoMessage() {}

func (x *GatewayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEvent.ProtoReflect.Descriptor instead.
func (*GatewayEvent) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayEvent) GetEvt() isGatewayEvent_Evt {
	if x != nil {
		return x.Evt
	}
	return nil
}

func (x *GatewayEvent) GetSessionOpen() *SessionOpen {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_SessionOpen); ok {
			return x.SessionOpen
		}
	}
	return nil
}

func (x *GatewayEvent) GetVadStart() *VADStart {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_VadStart); ok {
			return x.VadStart
		}
	}
	return nil
}

func (x *GatewayEvent) GetVadEnd() *VADEnd {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_VadEnd); ok {
			return x.VadEnd
		}
	}
	return nil
}

func (x *GatewayEvent) GetTranscriptInterim() *TranscriptInterim {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_TranscriptInterim); ok {
			return x.TranscriptInterim
		}
	}
	return nil
}

func (x *GatewayEvent) GetTranscriptFinal() *TranscriptFinal {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_TranscriptFinal); ok {
			return x.TranscriptFinal
		}
	}
	return nil
}

func (x *GatewayEvent) GetTts() *TTSEvent {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_Tts); ok {
			return x.Tts
		}
	}
	return nil
}

func (x *GatewayEvent) GetError() *GatewayError {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GatewayEvent) GetFrameTap() *FrameTap {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_FrameTap); ok {
			return x.FrameTap
		}
	}
	return nil
}

func (x *GatewayEvent) GetFeature() *Feature {
	if x != nil {
		if x, ok := x.Evt.(*GatewayEvent_Feature); ok {
			return x.Feature
		}
	}
	return nil
}

type isGatewayEvent_Evt interface {
	isGatewayEvent_Evt()
}

type GatewayEvent_SessionOpen struct {
	SessionOpen *SessionOpen `protobuf:"bytes,2,opt,name=session_open,json=sessionOpen,proto3,oneof"`
}

type GatewayEvent_VadStart struct {
	VadStart *VADStart `protobuf:"bytes,3,opt,name=vad_start,json=vadStart,proto3,oneof"`
}

type GatewayEvent_VadEnd struct {
	VadEnd *VADEnd `protobuf:"bytes,4,opt,name=vad_end,json=vadEnd,proto3,oneof"`
}

type GatewayEvent_TranscriptInterim struct {
	TranscriptInterim *TranscriptInterim `protobuf:"bytes,5,opt,name=transcript_interim,json=transcriptInterim,proto3,oneof"`
}

type GatewayEvent_TranscriptFinal struct {
	TranscriptFinal *TranscriptFinal `protobuf:"bytes,6,opt,name=transcript_final,json=transcriptFinal,proto3,oneof"`
}

type GatewayEvent_Tts struct {
	Tts *TTSEvent `protobuf:"bytes,7,opt,name=tts,proto3,oneof"`
}

type GatewayEvent_Error struct {
	Error *GatewayError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type GatewayEvent_FrameTap struct {
	FrameTap *FrameTap `protobuf:"bytes,9,opt,name=frame_tap,json=frameTap,proto3,oneof"`
}

type GatewayEvent_Feature struct {
	Feature *Feature `protobuf:"bytes,10,opt,name=feature,proto3,oneof"`
}

func (*GatewayEvent_SessionOpen) isGatewayEvent_Evt() {}

func (*GatewayEvent_VadStart) isGatewayEvent_Evt() {}

func (*GatewayEvent_VadEnd) isGatewayEvent_Evt() {}

func (*GatewayEvent_TranscriptInterim) isGatewayEvent_Evt() {}

func (*GatewayEvent_TranscriptFinal) isGatewayEvent_Evt() {}

func (*GatewayEvent_Tts) isGatewayEvent_Evt() {}

func (*GatewayEvent_Error) isGatewayEvent_Evt() {}

func (*GatewayEvent_FrameTap) isGatewayEvent_Evt() {}

func (*GatewayEvent_Feature) isGatewayEvent_Evt() {}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUrl       string                 `protobuf:"bytes,1,opt,name=room_url,json=roomUrl,proto3" json:"room_url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_gateway_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRoom) GetRoomUrl() string {
	if x != nil {
		return x.RoomUrl
	}
	return ""
}

func (x *JoinRoom) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StartMicToSTT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMicToSTT) Reset() {
	*x = StartMicToSTT{}
	mi := &file_gateway_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMicToSTT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMicToSTT) ProtoMessage() {}

func (x *StartMicToSTT) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMicToSTT.ProtoReflect.Descriptor instead.
func (*StartMicToSTT) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{11}
}

type StopMicToSTT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMicToSTT) Reset() {
	*x = StopMicToSTT{}
	mi := &file_gateway_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMicToSTT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMicToSTT) ProtoMessage() {}

func (x *StopMicToSTT) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMicToSTT.ProtoReflect.Descriptor instead.
func (*StopMicToSTT) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{12}
}

type StartTTS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTTS) Reset() {
	*x = StartTTS{}
	mi := &file_gateway_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTTS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTTS) ProtoMessage() {}

func (x *StartTTS) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTTS.ProtoReflect.Descriptor instead.
func (*StartTTS) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{13}
}

func (x *StartTTS) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StopTTS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTTS) Reset() {
	*x = StopTTS{}
	mi := &file_gateway_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTTS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTTS) ProtoMessage() {}

func (x *StopTTS) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTTS.ProtoReflect.Descriptor instead.
func (*StopTTS) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{14}
}

func (x *StopTTS) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ArmBargeIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuardMs       uint32                 `protobuf:"varint,1,opt,name=guard_ms,json=guardMs,proto3" json:"guard_ms,omitempty"`
	MinRms        uint32                 `protobuf:"varint,2,opt,name=min_rms,json=minRms,proto3" json:"min_rms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmBargeIn) Reset() {
	*x = ArmBargeIn{}
	mi := &file_gateway_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmBargeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmBargeIn) ProtoMessage() {}

func (x *ArmBargeIn) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmBargeIn.ProtoReflect.Descriptor instead.
func (*ArmBargeIn) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{15}
}

func (x *ArmBargeIn) GetGuardMs() uint32 {
	if x != nil {
		return x.GuardMs
	}
	return 0
}

func (x *ArmBargeIn) GetMinRms() uint32 {
	if x != nil {
		return x.MinRms
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_gateway_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{16}
}

func (x *Ack) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type OrchestratorCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*OrchestratorCommand_JoinRoom
	//	*OrchestratorCommand_StartMicToStt
	//	*OrchestratorCommand_StopMicToStt
	//	*OrchestratorCommand_StartTts
	//	*OrchestratorCommand_StopTts
	//	*OrchestratorCommand_ArmBargeIn
	//	*OrchestratorCommand_Ack
	Cmd           isOrchestratorCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorCommand) Reset() {
	*x = OrchestratorCommand{}
	mi := &file_gateway_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorCommand) ProtoMessage() {}

func (x *OrchestratorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorCommand.ProtoReflect.Descriptor instead.
func (*OrchestratorCommand) Descriptor() ([]byte, []int) {
	return file_gateway_control_proto_rawDescGZIP(), []int{17}
}

func (x *OrchestratorCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OrchestratorCommand) GetCmd() isOrchestratorCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *OrchestratorCommand) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetStartMicToStt() *StartMicToSTT {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_StartMicToStt); ok {
			return x.StartMicToStt
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetStopMicToStt() *StopMicToSTT {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_StopMicToStt); ok {
			return x.StopMicToStt
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetStartTts() *StartTTS {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_StartTts); ok {
			return x.StartTts
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetStopTts() *StopTTS {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_StopTts); ok {
			return x.StopTts
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetArmBargeIn() *ArmBargeIn {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_ArmBargeIn); ok {
			return x.ArmBargeIn
		}
	}
	return nil
}

func (x *OrchestratorCommand) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Cmd.(*OrchestratorCommand_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isOrchestratorCommand_Cmd interface {
	isOrchestratorCommand_Cmd()
}

type OrchestratorCommand_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,2,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type OrchestratorCommand_StartMicToStt struct {
	StartMicToStt *StartMicToSTT `protobuf:"bytes,3,opt,name=start_mic_to_stt,json=startMicToStt,proto3,oneof"`
}

type OrchestratorCommand_StopMicToStt struct {
	StopMicToStt *StopMicToSTT `protobuf:"bytes,4,opt,name=stop_mic_to_stt,json=stopMicToStt,proto3,oneof"`
}

type OrchestratorCommand_StartTts struct {
	StartTts *StartTTS `protobuf:"bytes,5,opt,name=start_tts,json=startTts,proto3,oneof"`
}

type OrchestratorCommand_StopTts struct {
	StopTts *StopTTS `protobuf:"bytes,6,opt,name=stop_tts,json=stopTts,proto3,oneof"`
}

type OrchestratorCommand_ArmBargeIn struct {
	ArmBargeIn *ArmBargeIn `protobuf:"bytes,7,opt,name=arm_barge_in,json=armBargeIn,proto3,oneof"`
}

type OrchestratorCommand_Ack struct {
	Ack *Ack `protobuf:"bytes,8,opt,name=ack,proto3,oneof"`
}

func (*OrchestratorCommand_JoinRoom) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_StartMicToStt) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_StopMicToStt) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_StartTts) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_StopTts) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_ArmBargeIn) isOrchestratorCommand_Cmd() {}

func (*OrchestratorCommand_Ack) isOrchestratorCommand_Cmd() {}

var File_gateway_control_proto protoreflect.FileDescriptor

const file_gateway_control_proto_rawDesc = "" +
	"\n" +
	"\x15gateway_control.proto\x12\n" +
	"gateway.v1\"G\n" +
	"\vSessionOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\broom_url\x18\x02 \x01(\tR\aroomUrl\"\x1f\n" +
	"\bVADStart\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x04R\x04tsMs\"\x1d\n" +
	"\x06VADEnd\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x04R\x04tsMs\"J\n" +
	"\x11TranscriptInterim\x12!\n" +
	"\futterance_id\x18\x01 \x01(\tR\vutteranceId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"H\n" +
	"\x0fTranscriptFinal\x12!\n" +
	"\futterance_id\x18\x01 \x01(\tR\vutteranceId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\\\n" +
	"\bTTSEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12$\n" +
	"\x0efirst_audio_ms\x18\x03 \x01(\rR\ffirstAudioMs\"<\n" +
	"\fGatewayError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\bFrameTap\x12\x16\n" +
	"\x06pcm48k\x18\x01 \x01(\fR\x06pcm48k\"\x1b\n" +
	"\aFeature\x12\x10\n" +
	"\x03rms\x18\x01 \x01(\x02R\x03rms\"\xb2\x04\n" +
	"\fGatewayEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12<\n" +
	"\fsession_open\x18\x02 \x01(\v2\x17.gateway.v1.SessionOpenH\x00R\vsessionOpen\x123\n" +
	"\tvad_start\x18\x03 \x01(\v2\x14.gateway.v1.VADStartH\x00R\bvadStart\x12-\n" +
	"\avad_end\x18\x04 \x01(\v2\x12.gateway.v1.VADEndH\x00R\x06vadEnd\x12N\n" +
	"\x12transcript_interim\x18\x05 \x01(\v2\x1d.gateway.v1.TranscriptInterimH\x00R\x11transcriptInterim\x12H\n" +
	"\x10transcript_final\x18\x06 \x01(\v2\x1b.gateway.v1.TranscriptFinalH\x00R\x0ftranscriptFinal\x12(\n" +
	"\x03tts\x18\a \x01(\v2\x14.gateway.v1.TTSEventH\x00R\x03tts\x120\n" +
	"\x05error\x18\b \x01(\v2\x18.gateway.v1.GatewayErrorH\x00R\x05error\x123\n" +
	"\tframe_tap\x18\t \x01(\v2\x14.gateway.v1.FrameTapH\x00R\bframeTap\x12/\n" +
	"\afeature\x18\n" +
	" \x01(\v2\x13.gateway.v1.FeatureH\x00R\afeatureB\x05\n" +
	"\x03evt\";\n" +
	"\bJoinRoom\x12\x19\n" +
	"\broom_url\x18\x01 \x01(\tR\aroomUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x0f\n" +
	"\rStartMicToSTT\"\x0e\n" +
	"\fStopMicToSTT\"\x1e\n" +
	"\bStartTTS\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"!\n" +
	"\aStopTTS\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"@\n" +
	"\n" +
	"ArmBargeIn\x12\x19\n" +
	"\bguard_ms\x18\x01 \x01(\rR\aguardMs\x12\x17\n" +
	"\amin_rms\x18\x02 \x01(\rR\x06minRms\"\x19\n" +
	"\x03Ack\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"\xc1\x03\n" +
	"\x13OrchestratorCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\tjoin_room\x18\x02 \x01(\v2\x14.gateway.v1.JoinRoomH\x00R\bjoinRoom\x12D\n" +
	"\x10start_mic_to_stt\x18\x03 \x01(\v2\x19.gateway.v1.StartMicToSTTH\x00R\rstartMicToStt\x12A\n" +
	"\x0fstop_mic_to_stt\x18\x04 \x01(\v2\x18.gateway.v1.StopMicToSTTH\x00R\fstopMicToStt\x123\n" +
	"\tstart_tts\x18\x05 \x01(\v2\x14.gateway.v1.StartTTSH\x00R\bstartTts\x120\n" +
	"\bstop_tts\x18\x06 \x01(\v2\x13.gateway.v1.StopTTSH\x00R\astopTts\x12:\n" +
	"\farm_barge_in\x18\a \x01(\v2\x16.gateway.v1.ArmBargeInH\x00R\n" +
	"armBargeIn\x12#\n" +
	"\x03ack\x18\b \x01(\v2\x0f.gateway.v1.AckH\x00R\x03ackB\x05\n" +
	"\x03cmd2Z\n" +
	"\x0eGatewayControl\x12H\n" +
	"\aSession\x12\x18.gateway.v1.GatewayEvent\x1a\x1f.gateway.v1.OrchestratorCommand(\x010\x01B/Z-yuzu/agent/internal/orchestrator/pb;gatewaypbb\x06proto3"

var (
	file_gateway_control_proto_rawDescOnce sync.Once
	file_gateway_control_proto_rawDescData []byte
)

func file_gateway_control_proto_rawDescGZIP() []byte {
	file_gateway_control_proto_rawDescOnce.Do(func() {
		file_gateway_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_control_proto_rawDesc), len(file_gateway_control_proto_rawDesc)))
	})
	return file_gateway_control_proto_rawDescData
}

var file_gateway_control_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gateway_control_proto_goTypes = []any{
	(*SessionOpen)(nil),         // 0: gateway.v1.SessionOpen
	(*VADStart)(nil),            // 1: gateway.v1.VADStart
	(*VADEnd)(nil),              // 2: gateway.v1.VADEnd
	(*TranscriptInterim)(nil),   // 3: gateway.v1.TranscriptInterim
	(*TranscriptFinal)(nil),     // 4: gateway.v1.TranscriptFinal
	(*TTSEvent)(nil),            // 5: gateway.v1.TTSEvent
	(*GatewayError)(nil),        // 6: gateway.v1.GatewayError
	(*FrameTap)(nil),            // 7: gateway.v1.FrameTap
	(*Feature)(nil),             // 8: gateway.v1.Feature
	(*GatewayEvent)(nil),        // 9: gateway.v1.GatewayEvent
	(*JoinRoom)(nil),            // 10: gateway.v1.JoinRoom
	(*StartMicToSTT)(nil),       // 11: gateway.v1.StartMicToSTT
	(*StopMicToSTT)(nil),        // 12: gateway.v1.StopMicToSTT
	(*StartTTS)(nil),            // 13: gateway.v1.StartTTS
	(*StopTTS)(nil),             // 14: gateway.v1.StopTTS
	(*ArmBargeIn)(nil),          // 15: gateway.v1.ArmBargeIn
	(*Ack)(nil),                 // 16: gateway.v1.Ack
	(*OrchestratorCommand)(nil), // 17: gateway.v1.OrchestratorCommand
}
var file_gateway_control_proto_depIdxs = []int32{
	0,  // 0: gateway.v1.GatewayEvent.session_open:type_name -> gateway.v1.SessionOpen
	1,  // 1: gateway.v1.GatewayEvent.vad_start:type_name -> gateway.v1.VADStart
	2,  // 2: gateway.v1.GatewayEvent.vad_end:type_name -> gateway.v1.VADEnd
	3,  // 3: gateway.v1.GatewayEvent.transcript_interim:type_name -> gateway.v1.TranscriptInterim
	4,  // 4: gateway.v1.GatewayEvent.transcript_final:type_name -> gateway.v1.TranscriptFinal
	5,  // 5: gateway.v1.GatewayEvent.tts:type_name -> gateway.v1.TTSEvent
	6,  // 6: gateway.v1.GatewayEvent.error:type_name -> gateway.v1.GatewayError
	7,  // 7: gateway.v1.GatewayEvent.frame_tap:type_name -> gateway.v1.FrameTap
	8,  // 8: gateway.v1.GatewayEvent.feature:type_name -> gateway.v1.Feature
	10, // 9: gateway.v1.OrchestratorCommand.join_room:type_name -> gateway.v1.JoinRoom
	11, // 10: gateway.v1.OrchestratorCommand.start_mic_to_stt:type_name -> gateway.v1.StartMicToSTT
	12, // 11: gateway.v1.OrchestratorCommand.stop_mic_to_stt:type_name -> gateway.v1.StopMicToSTT
	13, // 12: gateway.v1.OrchestratorCommand.start_tts:type_name -> gateway.v1.StartTTS
	14, // 13: gateway.v1.OrchestratorCommand.stop_tts:type_name -> gateway.v1.StopTTS
	15, // 14: gateway.v1.OrchestratorCommand.arm_barge_in:type_name -> gateway.v1.ArmBargeIn
	16, // 15: gateway.v1.OrchestratorCommand.ack:type_name -> gateway.v1.Ack
	9,  // 16: gateway.v1.GatewayControl.Session:input_type -> gateway.v1.GatewayEvent
	17, // 17: gateway.v1.GatewayControl.Session:output_type -> gateway.v1.OrchestratorCommand
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_gateway_control_proto_init() }
func file_gateway_control_proto_init() {
	if File_gateway_control_proto != nil {
		return
	}
	file_gateway_control_proto_msgTypes[9].OneofWrappers = []any{
		(*GatewayEvent_SessionOpen)(nil),
		(*GatewayEvent_VadStart)(nil),
		(*GatewayEvent_VadEnd)(nil),
		(*GatewayEvent_TranscriptInterim)(nil),
		(*GatewayEvent_TranscriptFinal)(nil),
		(*GatewayEvent_Tts)(nil),
		(*GatewayEvent_Error)(nil),
		(*GatewayEvent_FrameTap)(nil),
		(*GatewayEvent_Feature)(nil),
	}
	file_gateway_control_proto_msgTypes[17].OneofWrappers = []any{
		(*OrchestratorCommand_JoinRoom)(nil),
		(*OrchestratorCommand_StartMicToStt)(nil),
		(*OrchestratorCommand_StopMicToStt)(nil),
		(*OrchestratorCommand_StartTts)(nil),
		(*OrchestratorCommand_StopTts)(nil),
		(*OrchestratorCommand_ArmBargeIn)(nil),
		(*OrchestratorCommand_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_proto_rawDesc), len(file_gateway_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_control_proto_goTypes,
		DependencyIndexes: file_gateway_control_proto_depIdxs,
		MessageInfos:      file_gateway_control_proto_msgTypes,
	}.Build()
	File_gateway_control_proto = out.File
	file_gateway_control_proto_goTypes = nil
	file_gateway_control_proto_depIdxs = nil
}
