// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tts.proto

package ttspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	VoiceId       string                 `protobuf:"bytes,3,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"` // ElevenLabs voice id
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StartRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *StartRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{1}
}

func (x *Cancel) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Start
	//	*ClientMessage_Cancel
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientMessage) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Start struct {
	Start *StartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientMessage_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*ClientMessage_Start) isClientMessage_Msg() {}

func (*ClientMessage_Cancel) isClientMessage_Msg() {}

type Connected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connected) Reset() {
	*x = Connected{}
	mi := &file_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connected) ProtoMessage() {}

func (x *Connected) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connected.ProtoReflect.Descriptor instead.
func (*Connected) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{3}
}

func (x *Connected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm48K        []byte                 `protobuf:"bytes,1,opt,name=pcm48k,proto3" json:"pcm48k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_tts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{4}
}

func (x *AudioChunk) GetPcm48K() []byte {
	if x != nil {
		return x.Pcm48K
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Connected
	//	*ServerMessage_Audio
	//	*ServerMessage_Error
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_tts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_tts_proto_rawDescGZIP(), []int{6}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetConnected() *Connected {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *ServerMessage) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Connected struct {
	Connected *Connected `protobuf:"bytes,1,opt,name=connected,proto3,oneof"`
}

type ServerMessage_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Connected) isServerMessage_Msg() {}

func (*ServerMessage_Audio) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

var File_tts_proto protoreflect.FileDescriptor

const file_tts_proto_rawDesc = "" +
	"\n" +
	"\ttts.proto\x12\x06tts.v1\"{\n" +
	"\fStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\bvoice_id\x18\x03 \x01(\tR\avoiceId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"'\n" +
	"\x06Cancel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"n\n" +
	"\rClientMessage\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.tts.v1.StartRequestH\x00R\x05start\x12(\n" +
	"\x06cancel\x18\x02 \x01(\v2\x0e.tts.v1.CancelH\x00R\x06cancelB\x05\n" +
	"\x03msg\"*\n" +
	"\tConnected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"AudioChunk\x12\x16\n" +
	"\x06pcm48k\x18\x01 \x01(\fR\x06pcm48k\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\rServerMessage\x121\n" +
	"\tconnected\x18\x01 \x01(\v2\x11.tts.v1.ConnectedH\x00R\tconnected\x12*\n" +
	"\x05audio\x18\x02 \x01(\v2\x12.tts.v1.AudioChunkH\x00R\x05audio\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\r.tts.v1.ErrorH\x00R\x05errorB\x05\n" +
	"\x03msg2B\n" +
	"\x03TTS\x12;\n" +
	"\aSession\x12\x15.tts.v1.ClientMessage\x1a\x15.tts.v1.ServerMessage(\x010\x01B\"Z yuzu/agent/internal/tts/pb;ttspbb\x06proto3"

var (
	file_tts_proto_rawDescOnce sync.Once
	file_tts_proto_rawDescData []byte
)

func file_tts_proto_rawDescGZIP() []byte {
	file_tts_proto_rawDescOnce.Do(func() {
		file_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)))
	})
	return file_tts_proto_rawDescData
}

var file_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tts_proto_goTypes = []any{
	(*StartRequest)(nil),  // 0: tts.v1.StartRequest
	(*Cancel)(nil),        // 1: tts.v1.Cancel
	(*ClientMessage)(nil), // 2: tts.v1.ClientMessage
	(*Connected)(nil),     // 3: tts.v1.Connected
	(*AudioChunk)(nil),    // 4: tts.v1.AudioChunk
	(*Error)(nil),         // 5: tts.v1.Error
	(*ServerMessage)(nil), // 6: tts.v1.ServerMessage
}
var file_tts_proto_depIdxs = []int32{
	0, // 0: tts.v1.ClientMessage.start:type_name -> tts.v1.StartRequest
	1, // 1: tts.v1.ClientMessage.cancel:type_name -> tts.v1.Cancel
	3, // 2: tts.v1.ServerMessage.connected:type_name -> tts.v1.Connected
	4, // 3: tts.v1.ServerMessage.audio:type_name -> tts.v1.AudioChunk
	5, // 4: tts.v1.ServerMessage.error:type_name -> tts.v1.Error
	2, // 5: tts.v1.TTS.Session:input_type -> tts.v1.ClientMessage
	6, // 6: tts.v1.TTS.Session:output_type -> tts.v1.ServerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tts_proto_init() }
func file_tts_proto_init() {
	if File_tts_proto != nil {
		return
	}
	file_tts_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientMessage_Start)(nil),
		(*ClientMessage_Cancel)(nil),
	}
	file_tts_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_Connected)(nil),
		(*ServerMessage_Audio)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tts_proto_rawDesc), len(file_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tts_proto_goTypes,
		DependencyIndexes: file_tts_proto_depIdxs,
		MessageInfos:      file_tts_proto_msgTypes,
	}.Build()
	File_tts_proto = out.File
	file_tts_proto_goTypes = nil
	file_tts_proto_depIdxs = nil
}
