// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: stt.proto

package stt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_CONNECTION_FAILED      ErrorCode = 1
	ErrorCode_PROVIDER_ERROR         ErrorCode = 2
	ErrorCode_TIMEOUT                ErrorCode = 3
	ErrorCode_CIRCUIT_OPEN           ErrorCode = 4
	ErrorCode_INVALID_AUDIO          ErrorCode = 5
	ErrorCode_SHUTDOWN               ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "CONNECTION_FAILED",
		2: "PROVIDER_ERROR",
		3: "TIMEOUT",
		4: "CIRCUIT_OPEN",
		5: "INVALID_AUDIO",
		6: "SHUTDOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"CONNECTION_FAILED":      1,
		"PROVIDER_ERROR":         2,
		"TIMEOUT":                3,
		"CIRCUIT_OPEN":           4,
		"INVALID_AUDIO":          5,
		"SHUTDOWN":               6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_stt_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_stt_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

// Client -> Sidecar messages
type ControlStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                   // correlation across systems
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                      // origin python worker id (optional)
	UtteranceId     string                 `protobuf:"bytes,3,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`             // current utterance id
	Language        string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`                                      // e.g., en-US
	SampleRate      uint32                 `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`               // expected input (16k PCM16)
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // client protocol version
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControlStart) Reset() {
	*x = ControlStart{}
	mi := &file_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStart) ProtoMessage() {}

func (x *ControlStart) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStart.ProtoReflect.Descriptor instead.
func (*ControlStart) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{0}
}

func (x *ControlStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlStart) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ControlStart) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *ControlStart) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ControlStart) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *ControlStart) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm16K        []byte                 `protobuf:"bytes,1,opt,name=pcm16k,proto3" json:"pcm16k,omitempty"`                            // linear PCM16 mono @16kHz
	DurationMs    uint32                 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // optional, for metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetPcm16K() []byte {
	if x != nil {
		return x.Pcm16K
	}
	return nil
}

func (x *AudioChunk) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{2}
}

type SessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{3}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_stt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_stt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Start
	//	*ClientMessage_Audio
	//	*ClientMessage_Drain
	//	*ClientMessage_Close
	//	*ClientMessage_Ping
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_stt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetStart() *ControlStart {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientMessage) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ClientMessage) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ClientMessage) GetClose() *SessionClose {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Start struct {
	Start *ControlStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientMessage_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ClientMessage_Drain struct {
	Drain *Drain `protobuf:"bytes,3,opt,name=drain,proto3,oneof"`
}

type ClientMessage_Close struct {
	Close *SessionClose `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_Start) isClientMessage_Msg() {}

func (*ClientMessage_Audio) isClientMessage_Msg() {}

func (*ClientMessage_Drain) isClientMessage_Msg() {}

func (*ClientMessage_Close) isClientMessage_Msg() {}

func (*ClientMessage_Ping) isClientMessage_Msg() {}

// Sidecar -> Client messages
type Connected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // e.g., nova-2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connected) Reset() {
	*x = Connected{}
	mi := &file_stt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connected) ProtoMessage() {}

func (x *Connected) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connected.ProtoReflect.Descriptor instead.
func (*Connected) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{7}
}

func (x *Connected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Connected) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type TranscriptInterim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UtteranceId   string                 `protobuf:"bytes,2,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptInterim) Reset() {
	*x = TranscriptInterim{}
	mi := &file_stt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptInterim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptInterim) ProtoMessage() {}

func (x *TranscriptInterim) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptInterim.ProtoReflect.Descriptor instead.
func (*TranscriptInterim) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{8}
}

func (x *TranscriptInterim) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptInterim) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *TranscriptInterim) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscriptFinal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UtteranceId   string                 `protobuf:"bytes,2,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptFinal) Reset() {
	*x = TranscriptFinal{}
	mi := &file_stt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptFinal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptFinal) ProtoMessage() {}

func (x *TranscriptFinal) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptFinal.ProtoReflect.Descriptor instead.
func (*TranscriptFinal) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{9}
}

func (x *TranscriptFinal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptFinal) GetUtteranceId() string {
	if x != nil {
		return x.UtteranceId
	}
	return ""
}

func (x *TranscriptFinal) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // deprecated: use enum_code
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EnumCode      ErrorCode              `protobuf:"varint,4,opt,name=enum_code,json=enumCode,proto3,enum=stt.v1.ErrorCode" json:"enum_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_stt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetEnumCode() ErrorCode {
	if x != nil {
		return x.EnumCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	FramesSent    uint64                 `protobuf:"varint,3,opt,name=frames_sent,json=framesSent,proto3" json:"frames_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_stt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{11}
}

func (x *Metrics) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Metrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Metrics) GetFramesSent() uint64 {
	if x != nil {
		return x.FramesSent
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Connected
	//	*ServerMessage_Interim
	//	*ServerMessage_Final
	//	*ServerMessage_Error
	//	*ServerMessage_Pong
	//	*ServerMessage_Metrics
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_stt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_stt_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetConnected() *Connected {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *ServerMessage) GetInterim() *TranscriptInterim {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Interim); ok {
			return x.Interim
		}
	}
	return nil
}

func (x *ServerMessage) GetFinal() *TranscriptFinal {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Final); ok {
			return x.Final
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Connected struct {
	Connected *Connected `protobuf:"bytes,1,opt,name=connected,proto3,oneof"`
}

type ServerMessage_Interim struct {
	Interim *TranscriptInterim `protobuf:"bytes,2,opt,name=interim,proto3,oneof"`
}

type ServerMessage_Final struct {
	Final *TranscriptFinal `protobuf:"bytes,3,opt,name=final,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type ServerMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,6,opt,name=metrics,proto3,oneof"`
}

func (*ServerMessage_Connected) isServerMessage_Msg() {}

func (*ServerMessage_Interim) isServerMessage_Msg() {}

func (*ServerMessage_Final) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

func (*ServerMessage_Pong) isServerMessage_Msg() {}

func (*ServerMessage_Metrics) isServerMessage_Msg() {}

var File_stt_proto protoreflect.FileDescriptor

const file_stt_proto_rawDesc = "" +
	"\n" +
	"\tstt.proto\x12\x06stt.v1\"\xd5\x01\n" +
	"\fControlStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12!\n" +
	"\futterance_id\x18\x03 \x01(\tR\vutteranceId\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\rR\n" +
	"sampleRate\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\"E\n" +
	"\n" +
	"AudioChunk\x12\x16\n" +
	"\x06pcm16k\x18\x01 \x01(\fR\x06pcm16k\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\rR\n" +
	"durationMs\"\a\n" +
	"\x05Drain\"\x0e\n" +
	"\fSessionClose\"\x18\n" +
	"\x04Ping\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\xe9\x01\n" +
	"\rClientMessage\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.stt.v1.ControlStartH\x00R\x05start\x12*\n" +
	"\x05audio\x18\x02 \x01(\v2\x12.stt.v1.AudioChunkH\x00R\x05audio\x12%\n" +
	"\x05drain\x18\x03 \x01(\v2\r.stt.v1.DrainH\x00R\x05drain\x12,\n" +
	"\x05close\x18\x04 \x01(\v2\x14.stt.v1.SessionCloseH\x00R\x05close\x12\"\n" +
	"\x04ping\x18\x05 \x01(\v2\f.stt.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"@\n" +
	"\tConnected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"i\n" +
	"\x11TranscriptInterim\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\futterance_id\x18\x02 \x01(\tR\vutteranceId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"g\n" +
	"\x0fTranscriptFinal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\futterance_id\x18\x02 \x01(\tR\vutteranceId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x84\x01\n" +
	"\x05Error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\tenum_code\x18\x04 \x01(\x0e2\x11.stt.v1.ErrorCodeR\benumCode\"h\n" +
	"\aMetrics\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1f\n" +
	"\vframes_sent\x18\x03 \x01(\x04R\n" +
	"framesSent\"\xa9\x02\n" +
	"\rServerMessage\x121\n" +
	"\tconnected\x18\x01 \x01(\v2\x11.stt.v1.ConnectedH\x00R\tconnected\x125\n" +
	"\ainterim\x18\x02 \x01(\v2\x19.stt.v1.TranscriptInterimH\x00R\ainterim\x12/\n" +
	"\x05final\x18\x03 \x01(\v2\x17.stt.v1.TranscriptFinalH\x00R\x05final\x12%\n" +
	"\x05error\x18\x04 \x01(\v2\r.stt.v1.ErrorH\x00R\x05error\x12\"\n" +
	"\x04pong\x18\x05 \x01(\v2\f.stt.v1.PongH\x00R\x04pong\x12+\n" +
	"\ametrics\x18\x06 \x01(\v2\x0f.stt.v1.MetricsH\x00R\ametricsB\x05\n" +
	"\x03msg*\x92\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONNECTION_FAILED\x10\x01\x12\x12\n" +
	"\x0ePROVIDER_ERROR\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\x12\x10\n" +
	"\fCIRCUIT_OPEN\x10\x04\x12\x11\n" +
	"\rINVALID_AUDIO\x10\x05\x12\f\n" +
	"\bSHUTDOWN\x10\x062B\n" +
	"\x03STT\x12;\n" +
	"\aSession\x12\x15.stt.v1.ClientMessage\x1a\x15.stt.v1.ServerMessage(\x010\x01B Z\x1eyuzu/agent/internal/stt/pb;sttb\x06proto3"

var (
	file_stt_proto_rawDescOnce sync.Once
	file_stt_proto_rawDescData []byte
)

func file_stt_proto_rawDescGZIP() []byte {
	file_stt_proto_rawDescOnce.Do(func() {
		file_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)))
	})
	return file_stt_proto_rawDescData
}

var file_stt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_stt_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: stt.v1.ErrorCode
	(*ControlStart)(nil),      // 1: stt.v1.ControlStart
	(*AudioChunk)(nil),        // 2: stt.v1.AudioChunk
	(*Drain)(nil),             // 3: stt.v1.Drain
	(*SessionClose)(nil),      // 4: stt.v1.SessionClose
	(*Ping)(nil),              // 5: stt.v1.Ping
	(*Pong)(nil),              // 6: stt.v1.Pong
	(*ClientMessage)(nil),     // 7: stt.v1.ClientMessage
	(*Connected)(nil),         // 8: stt.v1.Connected
	(*TranscriptInterim)(nil), // 9: stt.v1.TranscriptInterim
	(*TranscriptFinal)(nil),   // 10: stt.v1.TranscriptFinal
	(*Error)(nil),             // 11: stt.v1.Error
	(*Metrics)(nil),           // 12: stt.v1.Metrics
	(*ServerMessage)(nil),     // 13: stt.v1.ServerMessage
}
var file_stt_proto_depIdxs = []int32{
	1,  // 0: stt.v1.ClientMessage.start:type_name -> stt.v1.ControlStart
	2,  // 1: stt.v1.ClientMessage.audio:type_name -> stt.v1.AudioChunk
	3,  // 2: stt.v1.ClientMessage.drain:type_name -> stt.v1.Drain
	4,  // 3: stt.v1.ClientMessage.close:type_name -> stt.v1.SessionClose
	5,  // 4: stt.v1.ClientMessage.ping:type_name -> stt.v1.Ping
	0,  // 5: stt.v1.Error.enum_code:type_name -> stt.v1.ErrorCode
	8,  // 6: stt.v1.ServerMessage.connected:type_name -> stt.v1.Connected
	9,  // 7: stt.v1.ServerMessage.interim:type_name -> stt.v1.TranscriptInterim
	10, // 8: stt.v1.ServerMessage.final:type_name -> stt.v1.TranscriptFinal
	11, // 9: stt.v1.ServerMessage.error:type_name -> stt.v1.Error
	6,  // 10: stt.v1.ServerMessage.pong:type_name -> stt.v1.Pong
	12, // 11: stt.v1.ServerMessage.metrics:type_name -> stt.v1.Metrics
	7,  // 12: stt.v1.STT.Session:input_type -> stt.v1.ClientMessage
	13, // 13: stt.v1.STT.Session:output_type -> stt.v1.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_stt_proto_init() }
func file_stt_proto_init() {
	if File_stt_proto != nil {
		return
	}
	file_stt_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientMessage_Start)(nil),
		(*ClientMessage_Audio)(nil),
		(*ClientMessage_Drain)(nil),
		(*ClientMessage_Close)(nil),
		(*ClientMessage_Ping)(nil),
	}
	file_stt_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerMessage_Connected)(nil),
		(*ServerMessage_Interim)(nil),
		(*ServerMessage_Final)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_Metrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stt_proto_rawDesc), len(file_stt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stt_proto_goTypes,
		DependencyIndexes: file_stt_proto_depIdxs,
		EnumInfos:         file_stt_proto_enumTypes,
		MessageInfos:      file_stt_proto_msgTypes,
	}.Build()
	File_stt_proto = out.File
	file_stt_proto_goTypes = nil
	file_stt_proto_depIdxs = nil
}
