// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: stt.proto

package stt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	STT_Session_FullMethodName = "/stt.v1.STT/Session"
)

// STTClient is the client API for STT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type STTClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type sTTClient struct {
	cc grpc.ClientConnInterface
}

func NewSTTClient(cc grpc.ClientConnInterface) STTClient {
	return &sTTClient{cc}
}

func (c *sTTClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &STT_ServiceDesc.Streams[0], STT_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STT_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// STTServer is the server API for STT service.
// All implementations must embed UnimplementedSTTServer
// for forward compatibility.
type STTServer interface {
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedSTTServer()
}

// UnimplementedSTTServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSTTServer struct{}

func (UnimplementedSTTServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedSTTServer) mustEmbedUnimplementedSTTServer() {}
func (UnimplementedSTTServer) testEmbeddedByValue()             {}

// UnsafeSTTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to STTServer will
// result in compilation errors.
type UnsafeSTTServer interface {
	mustEmbedUnimplementedSTTServer()
}

func RegisterSTTServer(s grpc.ServiceRegistrar, srv STTServer) {
	// If the following call panics, it indicates UnimplementedSTTServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&STT_ServiceDesc, srv)
}

func _STT_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(STTServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STT_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// STT_ServiceDesc is the grpc.ServiceDesc for STT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var STT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stt.v1.STT",
	HandlerType: (*STTServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _STT_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stt.proto",
}
